name: Exercise Workflow

on: [push]

jobs:
  style_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: psf/black@stable

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v2
      - name: "Install packages"
        run: |
          pip install pytest coverage
          pip install -r requirements.txt
      - name: "Run pytest with coverage"
        run: coverage run -m pytest
      - name: "Show local filestructure"
        run: ls -all
      - name: "Upload artifact"
        uses: actions/upload-artifact@v4
        with:
          name: coverage-file
          path: .coverage
          include-hidden-files: true
          retention-days: 1

  coverage_report:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v2
      - name: "Install packages"
        run: pip install coverage
      - name: "Download .coverage"
        uses: actions/download-artifact@v4
        with:
          name: coverage-file
      - name: "Create coverage report"
        run: |
          coverage report
          coverage xml
      - name: "Upload xml report"
        uses: actions/upload-artifact@v4
        with:
          name: coverage-xml-report
          path: coverage.xml
          retention-days: 14